version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@0.0.11

# build_package is the main build process. It builds and test our packages using given parameters.
# It also generates artifacts, coverage files, test results and etc.

jobs:
  build_package:
    parameters:
      package_name:
        type: string
      package_binary:
        type: string
      package_type:
        type: string
        default: service
      package_directory:
        type: string

    docker:
      - image: "circleci/golang:1.11"
    steps:
      - checkout

workflows:
  # Log into AWS, build and push image to Amazon ECR
  build_and_push_image:
    jobs:
      - build_package:
          package_name: partner
          package_binary: partner-service
          package_directory: ./partner
      - aws-ecr/build-and-push-image:
          requires:
            - build_package
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          # Name of dockerfile to use. Defaults to Dockerfile.
          dockerfile: partner/Dockerfile
          # AWS_REGION_ENV_VAR_NAME
          region: AWS_DEFAULT_REGION
          # ECR
          repo: "ze-delivery/partner-service"
          # myECRRepoTag
          tag: "$CIRCLE_SHA1"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_DEFAULT_REGION
          family: "partner-service"
          cluster-name: "ze-delivery-microservices-main"
          container-image-name-updates: "container=partner-service,tag=${CIRCLE_SHA1}"
